### ISSUE TITLE
No funciona en un contenedor docker.

### ISSUE THREAD

**Issue by benalb** [atareao/eh#2]
He creado este Dockerfile:

FROM ubuntu:latest
RUN apt-get update && apt-get install -y curl gcc libssl-dev pkg-config vim 
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
RUN /root/.cargo/bin/cargo install oye
RUN mkdir -p /root/.config/oye
COPY config.yml /root/.config/oye/config.yml

Cuando lanzo el contenedor e intento ejecutar oye

root@c6153c211d2a:~# oye
2023-03-31T11:14:07.988588Z  INFO oye: Question: 
⣇ 🤔  thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/oye-0.1.0/src/ia.rs:113:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Editado: para aclarar, el fichero config.yml que copio al contenedor contiene mi token de openai.

**Comment by benalb** [comment]
Parece ser que el problema está mi API_KEY, ya que he probado chatGPT-shell-cli y me da un error de "insufficient_quota".

**Comment by atareao** [comment]
Muchas gracias @benalb 

He corregido algunos detalles, entre e llos la captura de errores, para que muestre algo como

```
docker run -it --rm atareao/oye encuentra todos los archivos con extensión .yml
⡗ 🤔  Error: Incorrect API key provided: sk-kUF89****************************************fh4k. You can find your API key at https://platform.openai.com/account/api-keys.
```
